# Generated by Django 4.2.1 on 2023-06-15 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_efforts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete_per',
            field=models.FloatField(max_length=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
