# Generated by Django 4.2.1 on 2024-04-16 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_complete_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete_per',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Stuck'), ('2', 'Working'), ('3', 'Done')], default='1', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.CharField(choices=[('1', 'On Due'), ('2', 'Overdue'), ('3', 'Done')], default='1', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Stuck'), ('2', 'Working'), ('3', 'Done')], default='1', max_length=7),
        ),
    ]
