# Generated by Django 4.2.1 on 2023-06-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_userprofile_friends_churnpredictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnpredictionmodel',
            name='churn_percentage',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=5),
            preserve_default=False,
        ),
    ]
