# Generated by Django 4.2.1 on 2024-04-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_churnpredictionmodel_churn_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
    ]
